config/routes.rb
Rails.application.routes.draw do
  resources :menus
  devise_for :users, controllers: { registrations: "registrations" },
                     path: "",
                     path_names: { sign_in: "login",
                                   sign_out: "logout",
                                   sign_up: "register" }
  get "pages/home"
  get "pages/terms"
  resources :categories
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  paginates_per 5
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one_attached :image

  has_many :menu_saucers
  has_many :saucers, through: :menu_saucers

  enum status: { proceso: 0, preparado: 1 }
end

app/models/menu_saucer.rb
class MenuSaucer < ApplicationRecord
  # Relationships
  belongs_to :menu
  belongs_to :saucer

  # Validations
  validates :menu, :saucer, presence: true
end

app/models/saucer.rb
class Saucer < ApplicationRecord
  # Relationships
  has_many :menu_saucers
  has_many :menus, through: :menu_saucers

  # validations
  validates :name, presence: true
  validates :available, inclusion: { in: [true, false] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[Cliente Cliente_gordo Cliente_premium Auditor]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.order(:name).page params[:page]
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :available)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[ show edit update destroy ]

  # GET /menus or /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1 or /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus or /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully created." }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1 or /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully updated." }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1 or /menus/1.json
  def destroy
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url, notice: "Menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu
    @menu = Menu.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def menu_params
    params.require(:menu).permit(:name, :description, :category_id, :user_id, :status, { menu_saucer_ids: [] }, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def terms
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    added_attrs = %i[ email password password_confirmation remember_me
                      name bio category birthday
    ]

    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: %i[email password remember_me]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def after_update_path_for(resource)
    edit_user_registration_path(resource)
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= category.available %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :available, style: "display: block" %>
    <%= form.check_box :available %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>
<%= link_to "New category", new_category_path %>
<hr>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= paginate @categories %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>G2Restaurant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
  </head>
  <body>
    <main class="container">
      <%= link_to "Restaurant", root_path %>|
      <%= link_to "Menu", menus_path %>|
      <% if user_signed_in? %>
        <%= current_user.name %>
        <strong><%= (current_user.role) %></strong>
        <%= link_to t('.edit_profile'), edit_user_registration_path %>
        <%#= link_to t('.users'), users_path, class: "navbar-item" %>
        <%= link_to t('.sign_out'), destroy_user_session_path, 'data-turbo-method': :delete %>
      <% else %>
        <%= link_to t('.sign_up'), new_user_registration_path %>
        <%= link_to t('.sign_in'), new_user_session_path %>
      <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu) do |form| %>
  <% if menu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>
      <ul>
        <% menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id,
        Category.where(available: true),
        :id,
        :name,
        required: true,
        prompt: "--- Select a category ---" %>
  </div>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id,
        User.order(:name),
        :id,
        :name,
        required: true,
        prompt: "--- Select a user ---" %>
  </div>
  <div class="field">
    <%= form.label :saucers %>
    <%= form.collection_check_boxes(:saucer_ids,
                                    Saucer.where(available: true),
                                    :id,
                                    :name) do |b| %>
      <%= b.label class:"label-checkbox" do %>
        <%= b.check_box + b.text %>
      <%end%>
    <% end %>
  </div>
  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, Menu.statuses.keys.map { |w| [w.humanize, w] } %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<div id="<%= dom_id menu %>">
  <p>
    <strong>Imagen</strong>
    <%= image_tag menu.image %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= menu.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= menu.description %>
  </p>
  <p>
    <strong>Category:</strong>
    <%= menu.category.name %>
  </p>
  <p>
    <strong>User:</strong>
    <%= menu.user.name %>
  </p>
  <p>
    <strong>Saucers:</strong>
    <%= menu.saucers.map(&:name).sort.join(',') %>
  </p>
  <p>
    <strong>Status:</strong>
    <%= menu.status %>
  </p>
</div>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Show this menu", @menu %> |
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Menus</h1>

<div id="menus">
  <% @menus.each do |menu| %>
    <%= render menu %>
    <p>
      <%= link_to "Show this menu", menu %>
    </p>
  <% end %>
</div>

<%= link_to "New menu", new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu %>

<div>
  <%= link_to "Edit this menu", edit_menu_path(@menu) %> |
  <%= link_to "Back to menus", menus_path %>

  <%= button_to "Destroy this menu", @menu, method: :delete %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>